### ISSUE TITLE
Attribution not generated from long or messy Flickr search URL

### ISSUE THREAD

**Issue by billymeinke** [cogdog/flickr-cc-helper#3]
Found a photo after searching by keyword & license type, ended up with a messy URL . Bookmarklet wouldn't create the attribution (squirrels still spinning the turbines) until I grabbed a clean link from the "Share this photo" option and pasted it into the address bar.

![screen shot 2015-04-12 at 8 02 30 pm](https://cloud.githubusercontent.com/assets/3204193/7104841/f1d7da54-e14e-11e4-8ce7-ebf406a9406a.png)

Worth fixing?

Thx.

**Comment by cogdog** [comment]
Thanks Billy. My hunch is that the flickr api was temporarily not
available; I have seen this happen. I should probably do something to have
it time out if there is no response and generate a notice message.

All of the USL starting with /in/photolist-.... is just the context for a
search result that flickr uses to create the navigation icons below (so you
can page through search results). That has no effect on grabbing the
attribution info, the API and hence attributor gets the same result for
either
https://www.flickr.com/photos/tom_hall_nz/15158418383/in/photolist-p6uRF6-bvWoFB-5a2JJ9
or https://www.flickr.com/photos/tom_hall_nz/15158418383/

Here is a shot of it working

Thanks for letting me know, but I do not think it is anything on my side of
the code I can fix.
​

On Sun, Apr 12, 2015 at 1:03 AM, Billy Meinke notifications@github.com
wrote:

> Found a photo after searching by keyword & license type, ended up with a
> messy URL . Bookmarklet wouldn't create the attribution (squirrels still
> spinning the turbines) until I grabbed a clean link from the "Share this
> photo" option and pasted it into the address bar.
> 
> [image: screen shot 2015-04-12 at 8 02 30 pm]
> https://cloud.githubusercontent.com/assets/3204193/7104841/f1d7da54-e14e-11e4-8ce7-ebf406a9406a.png
> 
> Worth fixing?
> 
> Thx.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cogdog/flickr-cc-helper/issues/3.

## 

_--------------------------------------------------------------------Alan
Levine: A Cog, A Dog, A Blog_
cogdogblog.com • cogdog.info
StoryBox • cogdogblog.com/storybox

photoing on flickr http://flickr.com/photos/cogdog & Barking Dog Studios
http://barkingdog.me • tweeting @cogdog http://twitter.com/cogdog

## 50+ Web 2.0 Ways to Tell a Story -- 50ways.wikispaces.com
